**About Book Crossing Dataset**<br>

This dataset has been compiled by Cai-Nicolas Ziegler in 2004, and it comprises of three tables for users, books and ratings. Explicit ratings are expressed on a scale from 1-10 (higher values denoting higher appreciation) and implicit rating is expressed by 0.

Reference: http://www2.informatik.uni-freiburg.de/~cziegler/BX/ 

**Objective**

This project entails building a Book Recommender System for users based on user-based and item-based collaborative filtering approaches.

#### Execute the below cell to load the datasets

In [0]:
#Importing Libraries
import numpy as np
import pandas as pd


In [3]:
from google.colab import files
uploaded = files.upload()

Saving books.csv to books.csv


In [4]:
from google.colab import files
uploaded1 = files.upload()

Saving users.csv to users.csv


In [6]:
from google.colab import files
uploaded2 = files.upload()

Saving ratings.csv to ratings.csv


In [7]:
import io


#Loading data
books = pd.read_csv(io.BytesIO(uploaded['books.csv']), sep=";", error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']

users = pd.read_csv(io.BytesIO(uploaded1['users.csv']), sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']

ratings = pd.read_csv(io.BytesIO(uploaded2['ratings.csv']), sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:27

### Check no.of records and features given in each dataset

In [8]:
books.shape

(271360, 8)

In [9]:
users.shape

(278858, 3)

In [10]:
ratings.shape

(1149780, 3)

## Exploring books dataset

In [0]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  \
0    Mark P. O. Morford              2002     Oxford University Press   
1  Richard Bruce Wright              2001       HarperFlamingo Canada   
2          Carlo D'Este              1991             HarperPerennial   
3      Gina Bari Kolata              1999        Farrar Straus Giroux   
4       E. J. W. Barber              1999  W. W. Norton &amp; Company   

                                           imageUrlS  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlM  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlL  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

### Drop last three columns containing image URLs which will not be required for analysis

In [0]:
books = books.drop(["imageUrlS", "imageUrlM", "imageUrlL"], axis=1)

In [0]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  
0    Mark P. O. Morford              2002     Oxford University Press  
1  Richard Bruce Wright              2001       HarperFlamingo Canada  
2          Carlo D'Este              1991             HarperPerennial  
3      Gina Bari Kolata              1999        Farrar Straus Giroux  
4       E. J. W. Barber              1999  W. W. Norton &amp; Company

**yearOfPublication**

### Check unique values of yearOfPublication


In [0]:
books["yearOfPublication"].unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

As it can be seen from above that there are some incorrect entries in this field. It looks like Publisher names 'DK Publishing Inc' and 'Gallimard' have been incorrectly loaded as yearOfPublication in dataset due to some errors in csv file.


Also some of the entries are strings and same years have been entered as numbers in some places. We will try to fix these things in the coming questions.

### Check the rows having 'DK Publishing Inc' as yearOfPublication

In [12]:
books[books["yearOfPublication"] == "DK Publishing Inc"]

ISBN  ...                                          publisher
209538  078946697X  ...  http://images.amazon.com/images/P/078946697X.0...
221678  0789466953  ...  http://images.amazon.com/images/P/0789466953.0...

[2 rows x 5 columns]

In [0]:
#There are 2 rows having 'DK Publishing Inc' as year of publication

### Drop the rows having `'DK Publishing Inc'` and `'Gallimard'` as `yearOfPublication`

In [0]:
books[books["yearOfPublication"] == "Gallimard"]

ISBN                                          bookTitle  \
220731  2070426769  Peuple du ciel, suivi de 'Les Bergers\";Jean-M...   

       bookAuthor yearOfPublication  \
220731       2003         Gallimard   

                                                publisher  
220731  http://images.amazon.com/images/P/2070426769.0...

In [0]:
#There is 1 row having Gallimard as year of Publication

In [0]:
books.drop(books[books['yearOfPublication'] == "DK Publishing Inc"].index, inplace = True) 

In [0]:
books.shape

(271358, 5)

In [0]:
books.drop(books[books['yearOfPublication'] == "Gallimard"].index, inplace = True)

In [0]:
books.shape

(271357, 5)

### Change the datatype of yearOfPublication to 'int'

In [0]:
books.dtypes

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication    object
publisher            object
dtype: object

In [0]:
books["yearOfPublication"] = books["yearOfPublication"].astype("int32")

In [0]:
books.dtypes

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication     int32
publisher            object
dtype: object

### Drop NaNs in `'publisher'` column


In [16]:
 books[books["publisher"].isna()]

ISBN        bookTitle  ... yearOfPublication  publisher
128890  193169656X      Tyrant Moon  ...              2002        NaN
129037  1931696993  Finders Keepers  ...              2001        NaN

[2 rows x 5 columns]

In [0]:
#As the publisher is not known, we can replace the value with something else like 'other'

In [0]:
books.loc[(books["ISBN"] == '193169656X'), 'publisher' ] = 'other'
books.loc[(books["ISBN"] == '1931696993'), 'publisher' ] = 'other'

In [0]:
books[books["publisher"].isna()]

Empty DataFrame
Columns: [ISBN, bookTitle, bookAuthor, yearOfPublication, publisher]
Index: []

## Exploring Users dataset

In [0]:
print(users.shape)
users.head()

(278858, 3)


userID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

### Get all unique values in ascending order for column `Age`

In [18]:
np.sort(users["Age"].unique())

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 113., 114., 115., 116., 118., 119., 123., 124., 127.,
       128., 132., 133., 136., 137., 138., 140., 141., 143., 146., 147.,
       148., 151., 152., 156., 157., 159., 162., 168., 172., 175., 183.,
       186., 189., 199., 200., 201., 204., 207., 20

Age column has some invalid entries like nan, 0 and very high values like 100 and above

### Values below 5 and above 90 do not make much sense for our book rating case...hence replace these by NaNs

In [0]:
x

### Replace null values in column `Age` with mean

In [20]:
np.sort(users["Age"].unique())

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
       57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,
       70., 71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82.,
       83., 84., 85., 86., 87., 88., 89., 90., nan])

In [0]:
users["Age"] = users["Age"].fillna(users["Age"].mean())

### Change the datatype of `Age` to `int`

In [0]:
users["Age"] = users["Age"].astype("int64")

In [23]:
print(sorted(users.Age.unique()))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


## Exploring the Ratings Dataset

### check the shape

In [0]:
ratings.shape

(1149780, 3)

In [0]:
n_users = users.shape[0]
n_books = books.shape[0]

In [0]:
ratings.head(5)

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

### Ratings dataset should have books only which exist in our books dataset. Drop the remaining rows

In [0]:
ratings_books = ratings[ratings["ISBN"].isin(books["ISBN"])]

In [0]:
ratings_books.shape

(1031132, 3)

### Ratings dataset should have ratings from users which exist in users dataset. Drop the remaining rows

In [0]:
ratings_users = ratings_books[ratings_books["userID"].isin(users["userID"])]

In [0]:
ratings_users.shape

(1031132, 3)

### Consider only ratings from 1-10 and leave 0s in column `bookRating`

In [0]:
ratings_users.head()

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [94]:
ratings_users["bookRating"].unique()

array([ 0,  5,  3,  6,  7,  9,  8, 10,  1,  4,  2])

In [0]:
rating_new = ratings_users[ratings_users["bookRating"] != 0]

In [0]:
rating_new.shape

(383841, 3)

### Find out which rating has been given highest number of times

In [29]:
rating_new["bookRating"].groupby(rating_new["bookRating"]).count().sort_values(ascending=False)

bookRating
8     91804
10    71225
7     66401
9     60778
5     45355
6     31687
4      7617
3      5118
2      2375
1      1481
Name: bookRating, dtype: int64

In [0]:
#rating_new["bookRating"].value_counts()

In [0]:
#Observation : Rating "8" has been given highest number of times and has the maximum count value of 91804.

### **Collaborative Filtering Based Recommendation Systems**

### For more accurate results only consider users who have rated atleast 100 books

In [0]:
cnt = rating_new["userID"].value_counts()
rating1 = rating_new[rating_new["userID"].isin(cnt[cnt >= 100].index)]

In [31]:
rating1.shape

(103271, 3)

### Generating ratings matrix from explicit ratings


In [0]:
rating_mat = rating1.pivot(index="userID", columns="ISBN", values="bookRating").fillna(0)
userID = rating_mat.index
ISBN = rating_mat.columns

In [33]:
rating_mat.head()

ISBN    0000913154  0001046438  000104687X  ...  B00013AX9E  B0001I1KOG  B000234N3A
userID                                      ...                                    
2033           0.0         0.0         0.0  ...         0.0         0.0         0.0
2110           0.0         0.0         0.0  ...         0.0         0.0         0.0
2276           0.0         0.0         0.0  ...         0.0         0.0         0.0
4017           0.0         0.0         0.0  ...         0.0         0.0         0.0
4385           0.0         0.0         0.0  ...         0.0         0.0         0.0

[5 rows x 66574 columns]

#### Note: since NaNs cannot be handled by training algorithms, replace these by 0, which indicates absence of ratings

In [0]:
#NaNs filled with 0 in above step.

### Generate the predicted ratings using SVD with no.of singular values to be 50

In [0]:
from scipy.sparse.linalg import svds

In [0]:
U, sigma, Vt = svds(rating_mat, k = 50)

In [0]:
sigma

array([147.92121923, 149.34383594, 150.07402888, 152.20117656,
       152.87418704, 154.61308372, 154.8009367 , 155.9576219 ,
       158.05647521, 159.21079485, 159.81671145, 162.01964856,
       162.77851803, 163.33054935, 166.02489424, 166.8162491 ,
       168.04973155, 170.7748546 , 171.01325758, 173.2942917 ,
       174.57625311, 176.65730369, 178.61914388, 180.29517228,
       182.25079073, 184.10707214, 187.61690418, 189.75277078,
       190.96974587, 195.14643816, 199.83137575, 201.70083342,
       202.18713995, 203.48701648, 207.26450247, 209.9298699 ,
       213.23599152, 216.88280902, 224.26954903, 231.66187407,
       235.67096044, 249.95821298, 252.02931103, 261.24819623,
       267.9821169 , 281.01208736, 293.69539697, 379.58353138,
       634.74439146, 680.41331629])

In [0]:
sigma = np.diag(sigma)

In [37]:
sigma


array([[147.92121923,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 149.34383594,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 150.07402888, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 379.58353138,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
        634.74439146,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 680.41331629]])

In [0]:
all_users_predicted_ratings = np.dot(np.dot(U, sigma), Vt)

In [0]:
preds_df = pd.DataFrame(all_users_predicted_ratings, columns = rating_mat.columns)

In [40]:
preds_df

ISBN  0000913154  0001046438  000104687X  ...  B00013AX9E  B0001I1KOG  B000234N3A
0       0.025341   -0.002146   -0.001431  ...    0.000120   -0.001693    0.067503
1      -0.010012   -0.003669   -0.002446  ...   -0.000242    0.000029   -0.013059
2      -0.015054   -0.015457   -0.010304  ...   -0.000304    0.009009   -0.057692
3      -0.021499    0.035602    0.023735  ...    0.001981    0.031201   -0.046664
4       0.002077   -0.007965   -0.005310  ...    0.001413    0.004918    0.047773
..           ...         ...         ...  ...         ...         ...         ...
444    -0.013295   -0.002811   -0.001874  ...    0.001232   -0.024207    0.100999
445     0.017231    0.020953    0.013969  ...   -0.001817    0.008224   -0.071487
446     0.003814   -0.011141   -0.007427  ...    0.001740    0.008526    0.126062
447     0.078020   -0.024439   -0.016292  ...    0.000302    0.010178    0.035976
448     0.008056    0.011625    0.007750  ...    0.000086   -0.000324    0.007476

[449 rows x 66574 columns]

### Take a particular user_id

### Lets find the recommendations for user with id `2110`

#### Note: Execute the below cells to get the variables loaded

In [0]:
userID = 2110

In [0]:
user_id = 2 #2nd row in ratings matrix and predicted matrix

### Get the predicted ratings for userID `2110` and sort them in descending order

In [0]:
user_row_number = user_id - 1  #UserID starts at zero not 1
sorted_user_predictions = preds_df.loc[user_row_number].sort_values(ascending = False)

In [83]:
sorted_user_predictions

ISBN
059035342X    0.682443
0345370775    0.368945
0345384911    0.333624
043935806X    0.333209
044021145X    0.329336
                ...   
0671744577   -0.056397
0399141383   -0.057334
0553569783   -0.060981
0515127833   -0.061348
0553561618   -0.067188
Name: 1, Length: 66574, dtype: float64

### Create a dataframe with name `user_data` containing userID `2110` explicitly interacted books

In [0]:
user_data = rating1[rating1.userID == (userID)]

In [85]:
user_data.head()

userID        ISBN  bookRating
14448    2110  0060987529           7
14449    2110  0064472779           8
14450    2110  0140022651          10
14452    2110  0142302163           8
14453    2110  0151008116           5

In [86]:
user_data.shape

(103, 3)

In [0]:
#user_data.head()

userID        ISBN  bookRating
14448    2110  0060987529           7
14449    2110  0064472779           8
14450    2110  0140022651          10
14452    2110  0142302163           8
14453    2110  0151008116           5

In [0]:
#user_data.shape

(103, 3)

### Combine the user_data and and corresponding book data(`book_data`) in a single dataframe with name `user_full_info`

In [0]:
 book_data = books[books.ISBN.isin(user_data.ISBN)]

In [88]:
book_data.shape

(103, 5)

In [89]:
book_data.head()

ISBN  ...           publisher
246   0151008116  ...            Harcourt
904   015216250X  ...  Magic Carpet Books
1000  0064472779  ...        HarperTrophy
1302  0345307674  ...       Del Rey Books
1472  0671527215  ...              Pocket

[5 rows x 5 columns]

In [0]:
user_full_info = (user_data.merge(book_data, how = 'left', left_on = 'ISBN', right_on = 'ISBN'))              
                

In [91]:
user_full_info.head()

userID        ISBN  ...  yearOfPublication      publisher
0    2110  0060987529  ...               2000    Regan Books
1    2110  0064472779  ...               2003   HarperTrophy
2    2110  0140022651  ...               1965  Penguin Books
3    2110  0142302163  ...               2002   Puffin Books
4    2110  0151008116  ...               2002       Harcourt

[5 rows x 7 columns]

### Get top 10 recommendations for above given userID from the books not already rated by that user

In [0]:
num_recommendations = 10
recommendations = (books[~books['ISBN'].isin(user_full_info['ISBN'])].
                      merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
                           left_on = 'ISBN',
                           right_on = 'ISBN').
                      rename(columns = {user_row_number: 'Predictions'}).
                      sort_values('Predictions', ascending = False).
                      iloc[:num_recommendations, :-1])

In [93]:
# Top 10 recommendations for User ID -2110 which are not already  rated by that user.
recommendations

ISBN  ...                     publisher
1192  0345370775  ...              Ballantine Books
6184  0345384911  ...                 Del Rey Books
5458  043935806X  ...                    Scholastic
455   044021145X  ...  Bantam Dell Publishing Group
2031  0451151259  ...           Penguin Putnam~mass
5383  0439139597  ...                    Scholastic
3413  0439064872  ...                    Scholastic
976   0380759497  ...                           Eos
2435  0345353145  ...              Ballantine Books
6048  0451167317  ...                   Signet Book

[10 rows x 5 columns]